version: '3.9'

services:
  web:
    build: .
    container_name: django_app
    volumes:
      - media:/app/media
    expose:
      - "8080"  # Porta interna usada no Dockerfile

  nginx:
    image: nginx:latest
    container_name: nginx_media
    ports:
      - "8081:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - media:/app/media
    depends_on:
      - web
      
volumes:
  media:
