# Generated by Django 5.2 on 2025-04-13 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('dia', models.CharField(max_length=2)),
                ('mes', models.CharField(max_length=20)),
                ('horario', models.TimeField()),
                ('local', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Artigo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo_artigo', models.CharField(max_length=100)),
                ('categoria', models.CharField(max_length=100)),
                ('foto_artigo', models.ImageField(upload_to='artigo')),
                ('credito_foto_artigo', models.CharField(max_length=100)),
                ('autor_artigo', models.CharField(max_length=100)),
                ('data_publicacao_artigo', models.DateField(auto_now_add=True)),
                ('texto_artigo', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Diretoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_diretoria', models.CharField(max_length=100)),
                ('cargo', models.CharField(max_length=100)),
                ('foto_diretoria', models.ImageField(upload_to='diretoria')),
            ],
        ),
        migrations.CreateModel(
            name='Hero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo_hero', models.CharField(max_length=100)),
                ('descricao', models.TextField(max_length=350)),
                ('link', models.URLField()),
                ('imagen', models.ImageField(upload_to='hero')),
            ],
        ),
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo_noticia', models.CharField(max_length=100)),
                ('autor', models.CharField(max_length=100)),
                ('texto', models.TextField()),
                ('foto_noticia', models.ImageField(upload_to='noticia')),
                ('legenda_foto', models.CharField(max_length=200)),
                ('credito_foto', models.CharField(max_length=100)),
                ('olho', models.CharField(max_length=200)),
                ('tag', models.CharField(max_length=100)),
                ('data_publicacao', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
