# Generated by Django 5.2 on 2025-04-13 21:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="hero",
            old_name="imagen",
            new_name="imagem",
        ),
    ]
