# Generated by Django 5.2 on 2025-04-26 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_galeriapresidentes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Membro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_membro', models.CharField(max_length=200)),
                ('fotografia', models.ImageField(upload_to='membros')),
                ('biografia', models.TextField()),
            ],
        ),
    ]
